name: Auto Facebook Like

on:
  schedule:
    - cron: '0 13 * * *'  # Chạy hàng ngày 20:00 VN
  workflow_dispatch:

jobs:
  auto-like:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cài Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Cài thư viện hệ thống cho GUI
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxi6

      - name: Cài dependencies Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Chạy script Auto Like bằng cookie
        env:
          FB_COOKIE: ${{ secrets.FB_COOKIE }}
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" \
            python auto_like.py
