name: Auto Facebook Like

on:
  schedule:
    # Chạy mỗi ngày lúc 20:00 Asia/Ho_Chi_Minh = 13:00 UTC
    - cron: '0 13 * * *'
  workflow_dispatch:  # cho phép trigger thủ công

jobs:
  auto-like:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # cho phép chạy tối đa 3 giờ

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      - name: Cài Chromedriver
        uses: nanasess/setup-chromedriver@v1
        with:
          version: 'latest'

      - name: Run Auto-Like script
        env:
          FB_EMAIL: ${{ secrets.FB_EMAIL }}
          FB_PASSWORD: ${{ secrets.FB_PASSWORD }}
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" \
            python auto_like.py
