name: Auto Facebook Like

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  auto-like:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      # → Thay đổi ở đây:
      - name: Cài Chromedriver
        uses: actions/setup-chromedriver@v3
        with:
          chromedriver-version: 'latest'

      - name: Cài dependencies Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Chạy script Auto Like
        env:
          FB_EMAIL: ${{ secrets.FB_EMAIL }}
          FB_PASSWORD: ${{ secrets.FB_PASSWORD }}
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" \
            python auto_like.py
